# App name
sample:
  build: .
  command: sh start.sh
  volumes:
    - ../yebo-ember:/app/vendor/modules/yebo-ember
    - ../yebo_sdk:/app/vendor/modules/yebo_sdk
    - .:/app
  ports:
    - "4200:4200"
    - "49152:49152"
