# App name
sandbox:
  build: .
  command: sh start.sh
  volumes:
    - ../yebo-ember:/sandbox/vendor/modules/yebo-ember
    - ../yebo_sdk:/sandbox/vendor/modules/yebo_sdk
    - .:/sandbox
  ports:
    - "4200:4200"
    - "49152:49152"
